### ISSUE TITLE
Just doesnt work. 

### ISSUE THREAD

**Issue by zahidulinmarat** [nemanjan00/BadooNearbyLike#7]
May be because i have Warning in this piece of code:
`location.href = "javascript: ( function(){"     +      code +  "}) ()" ;`

**Comment by nemanjan00** [comment]
What kind of warning? Do menu elements appear?

**Comment by zahidulinmarat** [comment]
I attached 4 images so you can better understand.

**Comment by nemanjan00** [comment]
I did not get any images.

**Comment by zahidulinmarat** [comment]
![screenshot_22](https://user-images.githubusercontent.com/31965480/36546580-76537ea8-17f4-11e8-86e1-d3e6f271319d.png)
![screenshot_23](https://user-images.githubusercontent.com/31965480/36546581-7674fc04-17f4-11e8-850b-46ea989bbbd4.png)
![screenshot_24](https://user-images.githubusercontent.com/31965480/36546582-76b3c088-17f4-11e8-9521-1a5681c23e20.png)
![screenshot_25](https://user-images.githubusercontent.com/31965480/36546583-772bdf14-17f4-11e8-8ea8-a17204d1a962.png)

**Comment by nemanjan00** [comment]
This looks normal to me. 

Have you tried clicking on Mass Like and Mass Chat?

**Comment by zahidulinmarat** [comment]
So first i should press People-nearby and than  Mass-chat?

**Comment by nemanjan00** [comment]
You can start mass chat/mass like from any page.

**Comment by zahidulinmarat** [comment]
I see. You should do better description. First version i am using long time - thank you for that, it works great. Second version i was trying to run many times and did it only after chat with you.

**Comment by Octolus** [comment]
For me it throws https://i.imgur.com/kRRK82C.png

**Comment by Octolus** [comment]
got it to work, keeps throwing captcha tho

would be nice if it could be automated, 1 like every 1 second to prevent captcha so i can leave it running )

**Comment by nemanjan00** [comment]
Captcha is on visiting 100 profiles. 

I have a way to bypass that, but, you would lose quite a bit of matches that way since a lot of people do not have super powers and have no idea who liked them.

**Comment by ghost** [comment]
can anyone upload whole revision of script as new project?
thanks in advance

**Comment by nemanjan00** [comment]
Which revision?

**Comment by nemanjan00** [comment]
Which revision exacly?
